name: fabric_flutter
description: Native components and helpers
version: 1.9.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  devicelocale: ^0.8.2
  provider: ^6.1.5+1
  firebase_core: ^4.3.0
  cloud_firestore: ^6.1.1
  cloud_functions: ^6.0.5
  firebase_analytics: ^12.1.0
  firebase_auth: ^6.1.3
  firebase_messaging: ^16.1.0
  firebase_storage: ^13.0.5
  firebase_database: ^12.1.1
  json_annotation: ^4.9.0
  image_picker: ^1.2.1
  file_picker: ^10.3.8
  image: ^4.7.2
  google_sign_in: ^7.2.0
  http: ^1.6.0
  url_launcher: ^6.3.2
  google_maps_flutter: ^2.14.0
  package_info_plus: ^9.0.0
  mime: ^2.0.0
  universal_html: ^2.3.0
  video_player: ^2.10.1
  webview_flutter: ^4.13.1
  webview_flutter_android: ^4.10.11
  webview_flutter_wkwebview: ^3.23.5
  flutter_markdown: ^0.7.7+1
  connectivity_plus: ^7.0.0
  json_explorer: ^0.1.2
  web: ^1.1.1
  intl: ^0.20.2
  ansicolor: ^2.0.3
  json_serializable: ^6.11.3
  cupertino_icons: ^1.0.8
  google_fonts: ^7.0.1
  pointer_interceptor: ^0.10.1+2
  omni_datetime_picker: ^2.3.1
  collection: ^1.19.1
  dlibphonenumber: ^1.1.54
  scrollable_positioned_list: ^0.3.8
  gap: ^3.0.1
  google_sign_in_web: ^1.1.0
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5

dependency_overrides:
  intl: ^0.20.2
  web: ^1.1.1
#  http: ^1.2.1
#  firebase_core: 2.25.4
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
